#!/bin/sh

echo "Is it morning? Please answer yes or no ?"
read timeofday

case "$timeofday" in 
 yes)	echo "Good Morning";;
 no)	echo "Good Afternoon";;
 y)	echo "Good Morning";;
 n)	echo "Good Afternoon";;
 *)	echo "Sorry, answer not recognized";;
esac

echo "Are you man ? Please answer yes or no?"
read sex

case "$sex" in 
 yes | y | Yes | YES)	echo "Hi Man";;
 no | n | No | NO)	echo "Hi Woman";;
 *)			echo "Sorry, answer not recognized";;

esac

exit 0
