#!/bin/sh

sample_text="global variable"

foo(){
 local sample_text="local variable"
 echo "Function foo is exec"
 echo $sample_text

}

echo "script starting"
echo $sample_text

foo

echo "script ended"
echo $sample_text

yes_or_no(){
	
	echo "Is your name $*"
	while true
	do 
		echo -n "Enter yes or no"
		read x
		case "$x" in 
			[Yy] | [Yy][Ee][Ss] )	return 0;;
			n | no)						 return 1;;
			*) 								echo "Answer yes or no"
		esac
	done
}

echo "Original params are $*"

if  yes_or_no "$1"
then 
	echo "Hi $1, nice name"
else
	echo "never mind"
fi

exit 0