#!/bin/sh

if [ -f /bin/bash ]
then
 echo "file /bin/bash exists"
fi

if [ -d /bin/bash ]
then
 echo "/bin/bash is a dir"
else
 echo "bin/bash is not a dir"
fi

echo "Is it morning ? Please answer yes or no"
read timeofday

if [ $timeofday = "yes" ]: then
 echo "Good morning"
else
 echo "Good Afternoon"
fi
